#!/usr/bin/env bash

# Summarize git changes with Fabric
# Usage: aicommit [FILE]

set -e

FILE=$1

FABRIC_BIN="$HOME/.local/bin/fabric"

if [[ ! -x "$FABRIC_BIN" ]]; then
  echo "Error: fabric hasn't been properly installed"
  echo "👉 Please review ./scripts/readme.md to install"
  exit 1
fi

# Read `git diff` output
if [[ -n "$FILE" ]]; then
	DIFF_OUTPUT=$(git diff "$FILE")
else
	DIFF_OUTPUT=$(git diff) # Reads `git diff` for entire repo
fi

# Exit if there are no changes
if [[ -z "$DIFF_OUTPUT" ]]; then
	echo "🌱 No changes to commit..."
	exit 0
fi

COMMIT_MESSAGE=$(echo "$DIFF_OUTPUT" | fabric -p summarize_git_diff)

echo ""
echo "💾 Commiting changes with message:"
echo "$COMMIT_MESSAGE"
echo ""

git add "$FILE" && git commit -m "$COMMIT_MESSAGE" && git push


