#!/usr/bin/env bash

# Summarize git changes with Fabric
# Usage: aigd [FILE]

set -e

FILE=$1

FABRIC_BIN="$HOME/.local/bin/fabric"

if [[ ! -x "$FABRIC_BIN" ]]; then
  echo "Error: fabric hasn't been properly installed"
  echo "👉 Please review ./shortcuts/readme.md to install"
  exit 1
fi

# Read `git diff` output
if [[ -n "$FILE" ]]; then
	DIFF_OUTPUT=$(git diff "$FILE")
else
	DIFF_OUTPUT=$(git diff) # Reads `git diff` for entire repo
fi

# Exit if there are no changes
if [[ -z "$DIFF_OUTPUT" ]]; then
	echo "🌱 No changes to summarise..."
	exit 0
fi

echo "$DIFF_OUTPUT" | fabric -p summarize_git_diff

